.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PROMPT" "1" "April 2015" "" ""
.
.SH "NAME"
\fBprompt\fR \- consistant line editing
.
.SH "SYNOPSIS"
\fBprompt\fR [\fIcommand\fR\.\.\.]
.
.SH "DESCRIPTION"
\fBprompt\fR sits between your terminal and your shell session and notices when you are being prompted to enter a line\. Instead of the kernel canonical terminal mode, you edit the line with newline(1)\.
.
.SH "OPTIONS"
No options may be specified, executes \fIcommand\fR\.
.
.P
The line editing program may be overridden by placing a custom \fBnewline\fR early in your PATH\.
.
.SH "BUGS"
Lots\. This is pre\-release software\.
.
.SH "COPYRIGHT"
Public Domain
.
.SH "SEE ALSO"
newline(1)
